dotnet nuget push X3Code.Azure.Utils.1.5.0.nupkg --source X3Get
dotnet nuget push X3Code.Azure.Utils.1.5.6.nupkg --source X3Get
dotnet nuget push X3Code.Azure.Utils.1.6.0.nupkg --source X3Get
dotnet nuget push X3Code.Azure.Utils.1.6.2.nupkg --source X3Get
dotnet nuget push X3Code.Azure.Utils.1.7.0.nupkg --source X3Get
dotnet nuget push X3Code.Azure.Utils.1.7.2.nupkg --source X3Get
dotnet nuget push X3Code.Azure.Utils.1.8.0.nupkg --source X3Get
dotnet nuget push X3Code.Azure.Utils.1.8.2.nupkg --source X3Get
dotnet nuget push X3Code.Azure.Utils.1.8.3.nupkg --source X3Get

dotnet nuget push X3Code.Utilities.1.3.1.nupkg --source X3Get
dotnet nuget push X3Code.Utilities.1.3.2.nupkg --source X3Get
dotnet nuget push X3Code.Utilities.1.3.3.nupkg --source X3Get
dotnet nuget push X3Code.Utilities.1.5.0.nupkg --source X3Get
dotnet nuget push X3Code.Utilities.1.5.1.nupkg --source X3Get
dotnet nuget push X3Code.Utilities.1.5.2.nupkg --source X3Get
dotnet nuget push X3Code.Utilities.1.5.3.nupkg --source X3Get
dotnet nuget push X3Code.Utilities.1.5.4.nupkg --source X3Get
dotnet nuget push X3Code.Utilities.1.5.5.nupkg --source X3Get
dotnet nuget push X3Code.Utilities.1.5.6.nupkg --source X3Get
dotnet nuget push X3Code.Utilities.1.6.0.nupkg --source X3Get
dotnet nuget push X3Code.Utilities.1.6.2.nupkg --source X3Get
dotnet nuget push X3Code.Utilities.1.6.3.nupkg --source X3Get
dotnet nuget push X3Code.Utilities.1.7.0.nupkg --source X3Get
dotnet nuget push X3Code.Utilities.1.7.2.nupkg --source X3Get
dotnet nuget push X3Code.Utilities.1.8.0.nupkg --source X3Get
dotnet nuget push X3Code.Utilities.1.8.2.nupkg --source X3Get
dotnet nuget push X3Code.Utilities.1.8.3.nupkg --source X3Get

dotnet nuget push X3Code.Infrastructure.1.3.1.nupkg --source X3Get
dotnet nuget push X3Code.Infrastructure.1.3.2.nupkg --source X3Get
dotnet nuget push X3Code.Infrastructure.1.3.3.nupkg --source X3Get
dotnet nuget push X3Code.Infrastructure.1.3.4.nupkg --source X3Get
dotnet nuget push X3Code.Infrastructure.1.5.1.nupkg --source X3Get
dotnet nuget push X3Code.Infrastructure.1.5.2.nupkg --source X3Get
dotnet nuget push X3Code.Infrastructure.1.5.4.nupkg --source X3Get
dotnet nuget push X3Code.Infrastructure.1.5.5.nupkg --source X3Get
dotnet nuget push X3Code.Infrastructure.1.5.6.nupkg --source X3Get
dotnet nuget push X3Code.Infrastructure.1.6.0.nupkg --source X3Get
dotnet nuget push X3Code.Infrastructure.1.6.1.nupkg --source X3Get
dotnet nuget push X3Code.Infrastructure.1.6.2.nupkg --source X3Get
dotnet nuget push X3Code.Infrastructure.1.7.0.nupkg --source X3Get
dotnet nuget push X3Code.Infrastructure.1.7.2.nupkg --source X3Get
dotnet nuget push X3Code.Infrastructure.1.8.0.nupkg --source X3Get
dotnet nuget push X3Code.Infrastructure.1.8.2.nupkg --source X3Get
dotnet nuget push X3Code.Infrastructure.1.8.3.nupkg --source X3Get

dotnet nuget push X3Code.Wasm.Utils.1.8.2.nupkg --source X3Get

dotnet nuget push X3Code.Infrastructure.RavenDb.1.0.0.nupkg --source X3Get
dotnet nuget push X3Code.Infrastructure.RavenDb.1.0.2.nupkg --source X3Get
dotnet nuget push X3Code.Infrastructure.RavenDb.1.0.3.nupkg --source X3Get
dotnet nuget push X3Code.Infrastructure.RavenDb.1.0.4.nupkg --source X3Get
dotnet nuget push X3Code.Infrastructure.RavenDb.1.5.6.nupkg --source X3Get
